### ISSUE TITLE
co ćpałeś?

### ISSUE THREAD

**Issue by ghost** [ProgramistaZpolski/kg-to-toyota-corolla-conventer#1]
tak jak w tekście wyżej

**Comment by piotrbadelek** [comment]
1. nic
2. github mi nie przysłał maila o tym issue więc tak późno odpowiadam
3. jeśli chodzi o co chodzi z tym projektem, to na takim [kanale na youtubie](https://www.youtube.com/watch?v=WCRpxu5iNEk) jest poprostu mem że toyota corolla to uniwersalna jednostka pomiarów i stąd miałem pomysł na stworzenie tego konwentera
mam nadzieję że odpowiedziałem na wszystkie pytania

**Comment by piotrbadelek** [comment]
Can i close this issue?

**Comment by ghost** [comment]
Can you stop kurwa speak ponglish and be the zjebem

**Comment by piotrbadelek** [comment]
This is english but ok

Can i close this issue?

**Comment by ghost** [comment]
Nie rozumiem.

**Comment by piotrbadelek** [comment]
Please stop.

**Comment by ghost** [comment]
Co?
